SETTINGS:
  BLACKLIST_SLOTS:
    - 9
    - 10
    - 11
    - 12
  DEFAULT_SOUL: 5
  DEFAULT_SOUL_MAX: 10
  DEBUG: false
REHIBILITATE:
  ENABLE: true
  TIME: 300
  SOUL: 2
DEATH:
  SOUL_LOST: 1
  SKIP_DEATH_SCREEN: true
  LOSE_ITEM_WHEN_DEATH: true
  LOSE_ALL_ITEM: false
  MIN_SOUL_TO_LOSE: 3
PVP:
  ENABLE: true
  KILL_SOUL: 1
  CHANCE: 54.9
ITEM:
  SOUL:
    ENABLE: true
    MATERIAL: EMERALD
    SLOT: 8
    DATA: 0
    NAME: "&9%soul% Soul"
    UNBREAK: true
    GLOW: true
    HIDE_FLAG: true
    LORE:
      - "&7You have %soul% Soul"
MOBS:
  ENABLE: true #Kill mob to get soul
  ANIMAL: false #true -> Enable kill animal can get soul
  MONSTER: true
HOOK:
  MYTHICMOBS: true #You need bSoulMMAddon for this!

